# Generated by Django 5.1.3 on 2024-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
